galaxy_info:
  role_name: security
  description: Настройка сервера для работы с firewalld и iptables
  author: Magomedov Magomed
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
